from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'database-control$', include(admin.site.urls)),
	url(r'^$', 'NCCP.views.home', name='home'),
	url(r'^project$', 'NCCP.views.projectB', name='project'),
	url(r'^funding$', 'NCCP.views.projectF', name='funding'),
	url(r'^components$', 'NCCP.views.projectC', name='components'),
	url(r'^synergy$', 'NCCP.views.projectS', name='synergy'),
	url(r'^sensor$', 'NCCP.views.projectSensor', name='sensor'),
	url(r'^research$', 'NCCP.views.research', name='research'),
	url(r'^equipment$', 'NCCP.views.researchE', name='equipment'),
	url(r'^edetails$', 'NCCP.views.researchED', name='equipmentDetails'),
	url(r'^slist$', 'NCCP.views.researchSL', name='sensorList'),
	url(r'^locations$', 'NCCP.views.researchL', name='locations'),
	url(r'^dataresource$', 'NCCP.views.dataresource', name='dataResource'),
	url(r'^modeloutput$', 'NCCP.views.modeloutput', name='modelOutput'),
	url(r'^education$', 'NCCP.views.education', name='education'),
	url(r'^footprint$', 'NCCP.views.footprint', name='footprint'),
	url(r'^transect$', 'NCCP.views.transect', name='transect'),
	url(r'^conductivity$', 'NCCP.views.conductivity', name='conductivity'),
	url(r'^weather$', 'NCCP.views.weather', name='weather'),
	url(r'^wind$', 'NCCP.views.wind', name='wind'),
	url(r'^volumetric$', 'NCCP.views.volumetric', name='volumetric'),
	url(r'^clark$', 'NCCP.views.educationC', name='clark'),
	url(r'^washoe$', 'NCCP.views.educationW', name='washoe'),
	url(r'^secondary$', 'NCCP.views.educationS', name='secondary'),
	url(r'^losing-the-lake$', 'NCCP.views.education_ltl', name='losingTheLake'),
	url(r'^people$', 'NCCP.views.people', name='people'),
	url(r'^libraries$', 'NCCP.views.libraries_default', name='libraries'),
	url(r'^publications$', 'NCCP.views.libraries_publications', name='publications'),
	url(r'^pub-2012$', 'NCCP.views.libraries_publications_2012', name='publications2012'),
	url(r'^pub-2011$', 'NCCP.views.libraries_publications_2011', name='publications2011'),
	url(r'^pub-2010$', 'NCCP.views.libraries_publications_2010', name='publications2010'),
	url(r'^pub-2009$', 'NCCP.views.libraries_publications_2009', name='publications2009'),
	url(r'^photos-videos$', 'NCCP.views.libraries_photos_videos', name='photosVideos'),
	url(r'^tools$', 'NCCP.views.tools_default', name='tools'),
	url(r'^demeter$', 'NCCP.views.tools_demeter', name='demeter'),
	url(r'^sunprism$', 'NCCP.views.tools_sunprism', name='sunprism'),
	url(r'^webmit$', 'NCCP.views.tools_webmit', name='webmit'),
	url(r'^visted$', 'NCCP.views.tools_visted', name='visted'),
	url(r'^atmos$', 'NCCP.views.tools_atmos', name='atmos'),
	url(r'^contact_us$', 'NCCP.views.contact_us', name='contactUs'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
